/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cafe_project;

import connect.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ADMIN
 */
public class TableManagement1 extends javax.swing.JPanel {

    /**
     * Creates new form TableManagement1
     */
    Connection con;
    public TableManagement1() {
        initComponents();
        btnLuu.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        txtIdTable.setEnabled(false);
        txtTableName.setEnabled(false);
        txtArea.setEnabled(false);
        ButtonGroup group = new ButtonGroup();
        group.add(rdoBat);
        group.add(rdoTat);
        
        txtIdTable.setText(String.valueOf(getNextIdTable()));
        load_Table();
    }
    public int getNextIdTable() {
        int nextId = 1; // mặc định nếu bảng rỗng
        try {
            con = DatabaseConnection.getConnection();
            String sql = "SELECT IFNULL(MAX(IdTable), 0) + 1 AS NextID FROM tablemanagement";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                nextId = rs.getInt("NextID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nextId;
    }


    private void load_Table(){
        try {
            con = DatabaseConnection.getConnection();
            String sql = "Select * From tablemanagement";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) tblDisplayTable.getModel();
            tb.setRowCount(0);
            while(rs.next()){
                Vector vt = new Vector();
                vt.add(rs.getString("IdTable"));
                vt.add(rs.getString("TableName"));
                vt.add(rs.getString("Area"));
                vt.add(rs.getString("Status"));
                tb.addRow(vt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtIdTable = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtTableName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoBat = new javax.swing.JRadioButton();
        rdoTat = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnThemmoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        tblDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bàn", "Tên bàn", "Khu vực", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        txtTableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTableNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã bàn");

        jLabel2.setText("Số bàn");

        jLabel3.setText("Khu vực");

        jLabel4.setText("Trạng thái");

        rdoBat.setText("Bật");

        rdoTat.setText("Tắt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTableName, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txtIdTable))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rdoBat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdoTat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rdoBat)
                    .addComponent(rdoTat))
                .addGap(33, 33, 33))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThemmoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus (1)_1.png"))); // NOI18N
        btnThemmoi.setText("Thêm mới");
        btnThemmoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save-as-icon-22.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pen (1)_1.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setHideActionText(true);
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete (2).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1).png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/th (2).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnThemmoi)
                .addGap(18, 18, 18)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemmoi)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimkiem)
                        .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayTableMouseClicked
        int i = tblDisplayTable.getSelectedRow();
        txtIdTable.setText(tblDisplayTable.getValueAt(i, 0).toString());
        txtTableName.setText(tblDisplayTable.getValueAt(i, 1).toString());
        txtArea.setText(tblDisplayTable.getValueAt(i, 2).toString());
        String Status = tblDisplayTable.getValueAt(i, 3).toString();

        if (Status.equals("Bật")) {
            rdoBat.setSelected(true);
            rdoTat.setSelected(false); // nếu có nút tắt
        } else {
            rdoBat.setSelected(false);
            rdoTat.setSelected(true); // hoặc bỏ dòng này nếu không cần
        }
    }//GEN-LAST:event_tblDisplayTableMouseClicked

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTableNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTableNameActionPerformed
    private boolean CheckTrung(String tableName, String area) {
        try {
            String sql = "SELECT COUNT(*) FROM tablemanagement WHERE TableName = ? AND Area = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, tableName);
            ps.setString(2, area);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int count = rs.getInt(1);
                return count > 0; // true nếu đã tồn tại
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    private boolean isEmptyInput(String tableName, String area, JRadioButton rdoBat, JRadioButton rdoTat) {
        if (tableName == null || tableName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên bàn!");
            return true;
        }
        if (area == null || area.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Khu vực!");
            return true;
        }
        if (!rdoBat.isSelected() && !rdoTat.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Trạng thái (Bật hoặc Tắt)!");
            return true;
        }
        return false;
    }


    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            String TableName = txtTableName.getText();
            String Area = txtArea.getText();
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            if (isEmptyInput(TableName, Area, rdoBat, rdoTat)) {
                return;
            }

            if(CheckTrung(TableName, Area)){
                JOptionPane.showMessageDialog(this, "Tên bàn và khu vực đã tồn tại");
                return;
            }
            String sql = "INSERT INTO tablemanagement (TableName, Area, Status) VALUES (?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, TableName);
            ps.setString(2,Area);
            ps.setString(3, Status);
            ps.executeUpdate();
            load_Table();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công");
            
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            int i = tblDisplayTable.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
                return;
            }
            int IdTable = Integer.parseInt(txtIdTable.getText());
            String TableName = txtTableName.getText();
            String Area = txtArea.getText();
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            String sql = "Update tablemanagement set TableName = ?, Area = ?, Status = ? where IdTable = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(4, IdTable);
            ps.setString(1, TableName);
            ps.setString(2,Area);
            ps.setString(3, Status);
            ps.executeUpdate();
            load_Table();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int i = tblDisplayTable.getSelectedRow();
            if(i == -1){
                JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn dòng cần xóa");
                return;
            }
            else{
                int result = JOptionPane.showConfirmDialog(this, "Bạn có chắn chắn muốn xóa không", "Xóa",JOptionPane.YES_NO_OPTION );
                if(result == JOptionPane.NO_OPTION){
                    return;
                }
                else {
                    int IdTable = Integer.parseInt(txtIdTable.getText());
                    String sql = "Delete from tablemanagement where IdTable = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setInt(1, IdTable);
                    ps.executeUpdate();
                    load_Table();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        try {
            String TableName = txtTableName.getText();
            String Area = txtArea.getText();
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            String sql = "Select * From tablemanagement where TableName like ? and Area like ? and Status like ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, "%" + TableName + "%");
            ps.setString(2, "%" + Area + "%");
            ps.setString(3, "%" + Status + "%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) tblDisplayTable.getModel();
            tb.setRowCount(0);
            while(rs.next()){
                Vector vt = new Vector();
                vt.add(rs.getString("IdTable"));
                vt.add(rs.getString("TableName"));
                vt.add(rs.getString("Area"));
                vt.add(rs.getString("Status"));
                tb.addRow(vt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        btnLuu.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        
        txtIdTable.setEnabled(false);
        txtTableName.setEnabled(true);
        txtArea.setEnabled(true);
        
        txtIdTable.setText(String.valueOf(getNextIdTable()));
        txtTableName.setText("");
        txtArea.setText("");
    }//GEN-LAST:event_btnThemmoiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoBat;
    private javax.swing.JRadioButton rdoTat;
    private javax.swing.JTable tblDisplayTable;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtIdTable;
    private javax.swing.JTextField txtTableName;
    // End of variables declaration//GEN-END:variables
}
