/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cafe_project;

import connect.DatabaseConnection;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
//import org.apache.poi.ss.usermodel.*;
//import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;


/**
 *
 * @author ADMIN
 */
public class VoucherManagement1 extends javax.swing.JPanel {

    /**
     * Creates new form VoucherManagement1
     */
    Connection con;
    public VoucherManagement1() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        txtIdVoucher.setEnabled(false);
        txtCode.setEnabled(false);
        txtGiamGia.setEnabled(false);
        txtSoDiemDoi.setEnabled(false);
        group.add(rdoBat);
        group.add(rdoTat);
        load_voucher();
    }
    private void load_voucher(){
        try {
            con = DatabaseConnection.getConnection();
            String sql = "Select * from vouchermangement";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel)tblDisplayVoucher.getModel();
            tb.setRowCount(0);
            while(rs.next()){
                Vector vt = new Vector();
                vt.add(rs.getString("IdVoucher"));
                vt.add(rs.getString("Code"));
                vt.add(rs.getString("TrangThai"));
                vt.add(rs.getString("GiamGia"));
                vt.add(rs.getString("DiemDoi"));
                tb.addRow(vt);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VoucherManagement1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VoucherManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThemmoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayVoucher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtIdVoucher = new javax.swing.JTextField();
        txtSoDiemDoi = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoBat = new javax.swing.JRadioButton();
        rdoTat = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThemmoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus (1).png"))); // NOI18N
        btnThemmoi.setText("Thêm mới");
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save-as-icon-22.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pen (1)_1.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete (2).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1).png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/th (2).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnThemmoi)
                .addGap(18, 18, 18)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tblDisplayVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Voucher", "Code", "Trạng thái", "Giảm giá", "Điểm đổi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDisplayVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayVoucher);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        txtSoDiemDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDiemDoiActionPerformed(evt);
            }
        });

        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Voucher");

        jLabel2.setText("Mã Code");

        jLabel3.setText("Số Điểm Đổi");

        jLabel4.setText("Trạng thái");

        rdoBat.setText("Bật");

        rdoTat.setText("Tắt");

        jLabel5.setText("Giảm Giá");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txtIdVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdoBat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSoDiemDoi))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoDiemDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoBat)
                    .addComponent(rdoTat))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        txtIdVoucher.setEnabled(true);
        txtCode.setEnabled(true);
        txtGiamGia.setEnabled(true);
        txtSoDiemDoi.setEnabled(true);
        
        txtIdVoucher.setText("");
        txtCode.setText("");
        txtGiamGia.setText("");
        txtSoDiemDoi.setText("");
        
        btnLuu.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_btnThemmoiActionPerformed
    private boolean isEmptyVoucherInput(String id, String code, String discount, String pointText, JRadioButton rdoBat, JRadioButton rdoTat) {
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã voucher!");
            return true;
        }
        if (code == null || code.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Code!");
            return true;
        }
        if (discount == null || discount.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giảm giá!");
            return true;
        }
        if (pointText == null || pointText.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điểm đổi!");
            return true;
        }
        try {
            Integer.parseInt(pointText.trim()); // Kiểm tra có phải số không
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số điểm đổi phải là số!");
            return true;
        }
        if (!rdoBat.isSelected() && !rdoTat.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Trạng thái!");
            return true;
        }
        return false;
    }
    private boolean CheckTrung(String idVoucher, String code) {
    try {
        String sql = "SELECT COUNT(*) FROM vouchermangement WHERE IdVoucher = ? OR Code = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, idVoucher);
        ps.setString(2, code);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1) > 0;
        }
    } catch (SQLException ex) {
        Logger.getLogger(VoucherManagement1.class.getName()).log(Level.SEVERE, null, ex);
    }
    return false;
    }

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            String IdVoucher = txtIdVoucher.getText();
            String Code = txtCode.getText().trim();
            String GiamGia = txtGiamGia.getText();
            String DiemDoiText = txtSoDiemDoi.getText().trim();
            if (isEmptyVoucherInput(IdVoucher, Code, GiamGia, DiemDoiText, rdoBat, rdoTat)) {
                return;
            }
            int DiemDoi = Integer.parseInt(DiemDoiText);
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            if (CheckTrung(IdVoucher, Code)) {
                JOptionPane.showMessageDialog(this, "Mã voucher hoặc Code đã tồn tại!");
                return;
            }
            String sql = "Insert vouchermangement values(?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, IdVoucher);
            ps.setString(2, Code);
            ps.setString(3,Status);
            ps.setString(4, GiamGia);
            ps.setInt(5, DiemDoi);
            ps.executeUpdate();
            load_voucher();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công");
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            int i = tblDisplayVoucher.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
                return;
            }
            String IdVoucher = txtIdVoucher.getText();
            String Code = txtCode.getText().trim();
            String GiamGia = txtGiamGia.getText();
            String DiemDoiText = txtSoDiemDoi.getText().trim();
            if (isEmptyVoucherInput(IdVoucher, Code, GiamGia, DiemDoiText, rdoBat, rdoTat)) {
                return;
            }
            int DiemDoi = Integer.parseInt(DiemDoiText);
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            String sql = "Update vouchermangement set Code = ?, TrangThai = ?, GiamGia = ?, DiemDoi = ? where IdVoucher = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(5, IdVoucher);
            ps.setString(1, Code);
            ps.setString(2,Status);
            ps.setString(3, GiamGia);
            ps.setInt(4, DiemDoi);
            ps.executeUpdate();
            load_voucher();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int i = tblDisplayVoucher.getSelectedRow();
            if(i == -1){
                JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn dòng cần xóa");
                return;
            }
            else{
                int result = JOptionPane.showConfirmDialog(this, "Bạn có chắn chắn muốn xóa không", "Xóa",JOptionPane.YES_NO_OPTION );
                if(result == JOptionPane.NO_OPTION){
                    return;
                }
                else {
                    String IdVouvher = txtIdVoucher.getText();
                    String sql = "Delete from vouchermangement where IdVoucher = ?";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, IdVouvher);
                    ps.executeUpdate();
                    load_voucher();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
      try {
            String IdVoucher = txtIdVoucher.getText();
            String Code = txtCode.getText();
            String GiamGia = txtGiamGia.getText();
            String Point = txtSoDiemDoi.getText();
            String Status;
            if(rdoBat.isSelected()){
                Status = rdoBat.getText();
            }
            else{
                Status = rdoTat.getText();
            }
            String sql = "Select * From vouchermangement where IdVoucher like ? and Code like ? and TrangThai like ? and GiamGia like ? and DiemDoi like ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, "%" + IdVoucher + "%");
            ps.setString(2, "%" + Code + "%");
            ps.setString(3, "%" + Status + "%");
            ps.setString(4, "%" + GiamGia + "%");
            ps.setString(5, "%" + Point + "%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) tblDisplayVoucher.getModel();
            tb.setRowCount(0);
            while(rs.next()){
                Vector vt = new Vector();
                vt.add(rs.getString("IdVoucher"));
                vt.add(rs.getString("Code"));
                vt.add(rs.getString("TrangThai"));
                vt.add(rs.getString("GiamGia"));
                vt.add(rs.getString("DiemDoi"));
                tb.addRow(vt);
            }
       } catch (SQLException ex) {
           Logger.getLogger(TableManagement1.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void tblDisplayVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayVoucherMouseClicked
        int i = tblDisplayVoucher.getSelectedRow();
        txtIdVoucher.setText(tblDisplayVoucher.getValueAt(i, 0).toString());
        txtCode.setText(tblDisplayVoucher.getValueAt(i, 1).toString());
        txtGiamGia.setText(tblDisplayVoucher.getValueAt(i, 3).toString());
        txtSoDiemDoi.setText(tblDisplayVoucher.getValueAt(i, 4).toString());
        String Status = tblDisplayVoucher.getValueAt(i, 2).toString();

        if (Status.equals("Bật")) {
            rdoBat.setSelected(true);
            rdoTat.setSelected(false); // nếu có nút tắt
        } else {
            rdoBat.setSelected(false);
            rdoTat.setSelected(true); // hoặc bỏ dòng này nếu không cần
        }
    }//GEN-LAST:event_tblDisplayVoucherMouseClicked

    private void txtSoDiemDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDiemDoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDiemDoiActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoBat;
    private javax.swing.JRadioButton rdoTat;
    private javax.swing.JTable tblDisplayVoucher;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtIdVoucher;
    private javax.swing.JTextField txtSoDiemDoi;
    // End of variables declaration//GEN-END:variables
}
