/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import panel.MultiLineCellRenderer;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author Nguyen Van Chien
 */
public class History_orders extends javax.swing.JPanel {

    /**
     * Creates new form History_order
     */
    public History_orders() {
        initComponents();
          Loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn hàng"));

        jtb1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Ngày đặt hàng", "Trạng thái", "Mã nhân viên", "Mã bàn", "Phương thức mua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jtb1MouseDragged(evt);
            }
        });
        jtb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtb1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết đơn hàng"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Số lượng", "Mã món", "Mã đơn hàng", "Tên món", "Gía", "Tổng tiền"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(856, 856, 856))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jtb1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb1MouseDragged

    private void jtb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseClicked
        int selectedRow = jtb1.getSelectedRow();
        if (selectedRow >= 0) {
            long orderId = Long.parseLong(jtb1.getValueAt(selectedRow, 0).toString());
            loadOrderDetailsByOrderId(orderId);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtb1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        timKiemTheoNgay();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void Loaddata() {
    DefaultTableModel model = (DefaultTableModel) jtb1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    try (Connection conn = ConnectSQL.getConnection()) {
        String sql = "SELECT * FROM orders_history";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getLong("order_id"),
                rs.getTimestamp("order_time"),
                rs.getString("status"),
                rs.getLong("staff_id"),
                rs.getLong("table_id"),
                rs.getString("order_type")
            });
        }



    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi tải dữ liệu: " + e.getMessage());
    }
}
private void timKiemTheoNgay() {
    java.util.Date selectedDate = jDateChooser1.getDate();

    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày cần tìm!");
        return;
    }

    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String formattedDate = sdf.format(selectedDate);

    DefaultTableModel model = (DefaultTableModel) jtb1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    try (Connection conn = ConnectSQL.getConnection()) {
        String sql = "SELECT * FROM orders_history WHERE DATE(order_time) = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, formattedDate);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getLong("order_id"),
                rs.getTimestamp("order_time"),
                rs.getString("status"),
                rs.getLong("staff_id"),
                rs.getLong("table_id"),
                rs.getString("order_type")
            });
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không có đơn hàng nào vào ngày " + formattedDate);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage());
    }
}
    
//    private void loadDataGroupedByOrder() {
//    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//    tableModel.setRowCount(0);  // Làm sạch bảng trước khi cập nhật
//
//    try (Connection conn = javacuoiki.ConnectSQL.getConnection()) {
//        if (conn != null) {
//            // Truy vấn tất cả các đơn hàng, sắp xếp theo order_id
//            String query = "SELECT * FROM order_item_history ORDER BY order_id";  // Truy vấn tất cả các đơn hàng, sắp xếp theo order_id
//            try (PreparedStatement stmt = conn.prepareStatement(query)) {
//                ResultSet rs = stmt.executeQuery();
//                long previousOrderId = -1; // Khởi tạo trước là không có order_id
//                StringBuilder items = new StringBuilder(); // Chứa danh sách món ăn
//                StringBuilder quantities = new StringBuilder(); // Chứa số lượng món ăn
//                StringBuilder prices = new StringBuilder(); // Chứa giá món ăn
//                StringBuilder menuItemIds = new StringBuilder(); // Chứa menu_item_id
//                double totalAmount = 0; // Tổng tiền cho mỗi order
//
//                while (rs.next()) {
//                    long orderId = rs.getLong("order_id");
//                    long menuItemId = rs.getLong("menu_item_id"); // Lấy menu_item_id
//                    String name = rs.getString("name");
//                    int quantity = rs.getInt("quantity");
//                    double price = rs.getDouble("price");
//
//                    // Nếu orderId thay đổi thì mới thêm một dòng mới vào bảng
//                    if (orderId != previousOrderId && previousOrderId != -1) {
//                        // Thêm dữ liệu cho order cũ vào bảng
//                        tableModel.addRow(new Object[]{
//                                quantities.toString(),       // Số lượng
//                                menuItemIds.toString(),      // menu_item_id
//                                previousOrderId,             // Order ID
//                                items.toString(),            // Tên món ăn
//                                prices.toString(),           // Giá món ăn
//                                totalAmount                  // Tổng tiền cho toàn bộ món ăn trong đơn hàng
//                        });
//                        items.setLength(0); // Reset items
//                        quantities.setLength(0); // Reset quantities
//                        prices.setLength(0); // Reset prices
//                        menuItemIds.setLength(0); // Reset menuItemIds
//                        totalAmount = 0; // Reset tổng tiền
//                    }
//
//                    // Cập nhật dữ liệu cho món ăn trong cùng một order_id
//                    items.append(name).append("\n");  // Thêm món ăn mới với \n
//                    quantities.append(quantity).append("\n");  // Thêm số lượng mới với \n
//                    prices.append(price).append("\n");  // Thêm giá món ăn mới với \n
//                    menuItemIds.append(menuItemId).append("\n"); // Thêm menu_item_id mới với \n
//
//                    previousOrderId = orderId;
//                }
//
//                if (previousOrderId != -1) {
//                    tableModel.addRow(new Object[]{
//                            quantities.toString(),        // Số lượng
//                            menuItemIds.toString(),       // menu_item_id
//                            previousOrderId,              // Order ID
//                            items.toString(),             // Tên món ăn
//                            prices.toString(),            // Giá món ăn
//                            totalAmount                   // Tổng tiền cho toàn bộ món ăn trong đơn hàng
//                    });
//                }
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
//        }
//    } catch (SQLException e) {
//        e.printStackTrace();
//    }
//
//    // Cập nhật lại bảng sau khi thêm dữ liệu
//    jTable1.setModel(tableModel);
//    
//    // Áp dụng renderer cho JTable
//    jTable1.setDefaultRenderer(Object.class, new javacuoiki.MultiLineCellRenderer());
//    
//    // Tự động thay đổi chiều cao hàng
//    setRowHeight(jTable1);
//}
    private void setRowHeight(JTable table) {
    for (int row = 0; row < table.getRowCount(); row++) {
        int rowHeight = 0;
        for (int column = 0; column < table.getColumnCount(); column++) {
            TableCellRenderer renderer = table.getCellRenderer(row, column);
            Component comp = table.prepareRenderer(renderer, row, column);
            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
        }
        table.setRowHeight(row, rowHeight);
    }
    }
    private void loadOrderDetailsByOrderId(long orderId) {
    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    tableModel.setRowCount(0);  // Xóa dữ liệu cũ

    try (Connection conn = ConnectSQL.getConnection()) {
        String query = "SELECT * FROM order_item_history WHERE order_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setLong(1, orderId);
            ResultSet rs = stmt.executeQuery();

            StringBuilder items = new StringBuilder();
            StringBuilder quantities = new StringBuilder();
            StringBuilder prices = new StringBuilder();
            StringBuilder menuItemIds = new StringBuilder();
            double totalAmount = 0;

            while (rs.next()) {
                long menuItemId = rs.getLong("menu_item_id");
                String name = rs.getString("name");
                int quantity = rs.getInt("quantity");
                double price = rs.getDouble("price");

                items.append(name).append("\n");
                quantities.append(quantity).append("\n");
                prices.append(price).append("\n");
                menuItemIds.append(menuItemId).append("\n");
                totalAmount += price * quantity;
            }

            if (items.length() > 0) {
                tableModel.addRow(new Object[]{
                    quantities.toString(),
                    menuItemIds.toString(),
                    orderId,
                    items.toString(),
                    prices.toString(),
                    totalAmount
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    jTable1.setModel(tableModel);
    jTable1.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
    setRowHeight(jTable1);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtb1;
    // End of variables declaration//GEN-END:variables
}
