/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import cafe_project.*;
import panel.*;
import panel.DatabaseHelper;
import panel.ConnectSQL;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author Nguyen Van Chien
 */
public class order_item extends javax.swing.JPanel {
private DatabaseHelper dbHelper;
    private MenuItem selectedMenuItem = null;  // Món ăn được chọn
    private int selectedMenuItemQuantity = 1;
    private long selectedMenuItemId = -1;  // Lưu ID của món ăn được chọn, khởi tạo bằng -1 để kiểm tra khi chưa chọn món ăn
    private double selectedMenuItemPrice = 0.0; 
    private String selectedMenuItemName = "";
    DefaultListModel<String> modelList2 = new DefaultListModel<>();
    private long orderId = 0;
    /**
     * Creates new form order_item
     */
    public order_item() {
        initComponents();
        //setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dbHelper = new DatabaseHelper();       
        loadMenuItems();
        loadDataGroupedByOrder();
        
        customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jtfsl = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Số lượng", "Mã món", "Mã đơn hàng", "Tên món", "Gía món", "Tổng tiền"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("Tìm kiếm  theo mã đơn hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách món ăn"));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel2.setText("Nhập số lượng:");

        jtfsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfslActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jtfsl))))
                .addGap(144, 144, 144)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jLabel1.setText("Món đang chọn là:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();  // Lấy chỉ mục dòng được chọn

        // Kiểm tra nếu có dòng nào được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị của cột "Order ID" từ dòng được chọn
            long selectedOrderId = (long) jTable1.getValueAt(selectedRow, 2);  // Cột thứ 6 là "Order ID"
            // Lưu order_id vào biến toàn cục để sử dụng sau
            orderId = selectedOrderId;

            // Hiển thị hoặc thực hiện hành động khác với order_id
            System.out.println("Order ID được chọn: " + orderId);
        }        // TODO add your handling code here:
        updateRowHeights(jTable1); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        searchOrderItemsByOrderId();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        // Kiểm tra nếu có dòng nào được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị của cột "Order ID" từ dòng được chọn
            long orderId = (long) jTable1.getValueAt(selectedRow, 2);  // Cột thứ 2 là "Order ID"

            // Truy vấn tất cả các món ăn trong đơn hàng đó
            DefaultListModel<String> listModel = new DefaultListModel<>();
            try (Connection conn = ConnectSQL.getConnection()) {
                String query = "SELECT name FROM order_item WHERE order_id = ?";
                try (PreparedStatement stmt = conn.prepareStatement(query)) {
                    stmt.setLong(1, orderId);
                    ResultSet rs = stmt.executeQuery();

                    // Duyệt qua tất cả món ăn trong đơn hàng và thêm vào listModel
                    while (rs.next()) {
                        String itemName = rs.getString("name");
                        listModel.addElement(itemName);
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

            // Hiển thị hộp thoại để người dùng chọn món ăn cần xóa
            JList<String> itemList = new JList<>(listModel);
            itemList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            JOptionPane.showMessageDialog(this, new JScrollPane(itemList), "Chọn món ăn cần xóa", JOptionPane.PLAIN_MESSAGE);

            // Nếu người dùng chọn món ăn
            String selectedItem = itemList.getSelectedValue();
            if (selectedItem != null) {
                // Xóa món ăn được chọn
                deleteItemFromOrder(selectedItem, orderId);
                loadDataGroupedByOrder();  // Cập nhật lại dữ liệu trong JTable
                customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn một đơn hàng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow(); // Lấy dòng được chọn
        if (selectedRow >= 0) {
            long orderId = (long) jTable1.getValueAt(selectedRow, 2);  // Lấy order_id
            String itemNames = (String) jTable1.getValueAt(selectedRow, 3);  // Tên món ăn
            String itemQuantities = (String) jTable1.getValueAt(selectedRow, 0);  // Số lượng

            String[] names = itemNames.split("\n");
            String[] quantities = itemQuantities.split("\n");

            DefaultListModel<String> listModel = new DefaultListModel<>();
            for (int i = 0; i < names.length; i++) {
                listModel.addElement(names[i] + " - " + quantities[i]);
            }

            JList<String> list = new JList<>(listModel);
            list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            JScrollPane scrollPane = new JScrollPane(list);

            int option = JOptionPane.showConfirmDialog(this, scrollPane, "Chọn món ăn để sửa", JOptionPane.OK_CANCEL_OPTION);

            if (option == JOptionPane.OK_OPTION) {
                String selectedItem = list.getSelectedValue();
                if (selectedItem != null) {
                    String[] parts = selectedItem.split(" - ");
                    String itemName = parts[0].trim();  // Cắt khoảng trắng
                    String quantityStr = parts[1].trim();

                    // Kiểm tra nếu là dòng "Không có món"
                    if (itemName.equals("--Không có món--")) {
                        JOptionPane.showMessageDialog(this, "Món này không thể sửa vì đây là đơn hàng rỗng.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    JTextField txtNewQuantity = new JTextField();
                    JPanel panel = new JPanel(new GridLayout(2, 2));
                    panel.add(new JLabel("Món ăn:"));
                    panel.add(new JLabel(itemName));
                    panel.add(new JLabel("Số lượng mới:"));
                    panel.add(txtNewQuantity);

                    int confirm = JOptionPane.showConfirmDialog(this, panel, "Nhập số lượng mới", JOptionPane.OK_CANCEL_OPTION);

                    if (confirm == JOptionPane.OK_OPTION) {
                        String input = txtNewQuantity.getText().trim();
                        try {
                            int newQuantity = Integer.parseInt(input);

                            if (newQuantity <= 0) {
                                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            } else {
                                updateMenuItemQuantity(itemName, orderId, newQuantity);
                                loadDataGroupedByOrder();
                                customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
                                JOptionPane.showMessageDialog(this, "Sửa số lượng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            }
                        } catch (NumberFormatException ex) {
                            JOptionPane.showMessageDialog(this, "Vui lòng nhập số nguyên hợp lệ!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn để sửa", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (selectedMenuItemId == -1) {
            // Nếu chưa chọn món ăn
            JOptionPane.showMessageDialog(this, "Hãy chọn món ăn trước khi thêm vào đơn hàng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (orderId == 0) {
            // Nếu chưa chọn đơn hàng
            JOptionPane.showMessageDialog(this, "Hãy chọn đơn hàng trước khi thêm món ăn.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            // Kiểm tra nếu số lượng hợp lệ
            try {
                int quantity = Integer.parseInt(jtfsl.getText());  // Lấy số lượng từ trường nhập liệu

                // Kiểm tra nếu số lượng là số dương
                if (quantity > 0) {
                    // Thêm món ăn vào bảng order_item
                    addItemToOrder(selectedMenuItemId, quantity, selectedMenuItemPrice, selectedMenuItemName, orderId);
                    // Cập nhật JTable hoặc JList với món ăn đã thêm vào đơn hàng
                    loadDataGroupedByOrder();  // Cập nhật lại dữ liệu trong JTable
                    customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!

                    jtfsl.setText("");  // Reset về rỗng

                } else {
                    // Nếu số lượng không phải là số dương
                    JOptionPane.showMessageDialog(this, "Số lượng món ăn phải là số dương.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Nếu không phải số hợp lệ
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho số lượng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int selectedIndex = jList1.getSelectedIndex();  // Lấy chỉ mục món ăn được chọn trong jList1
        if (selectedIndex >= 0) {
            // Lấy tên món ăn từ jList1
            String selectedItem = jList1.getSelectedValue();

            // Tìm món ăn trong danh sách menuItems dựa trên tên món ăn
            MenuItem selectedMenuItem = getMenuItemByName(selectedItem);

            // Nếu tìm thấy món ăn
            if (selectedMenuItem != null) {
                // Lưu thông tin món ăn
                selectedMenuItemId = selectedMenuItem.getId();  // Lưu ID của món ăn
                selectedMenuItemPrice = selectedMenuItem.getPrice();  // Lưu giá của món ăn
                selectedMenuItemName = selectedMenuItem.getName();  // Lưu tên món ăn

                jList1.setSelectionBackground(Color.CYAN);  // Màu nền của mục được chọn
                jList1.setSelectionForeground(Color.BLACK);  // Màu chữ của mục được chọn
                jTextField2.setText(selectedMenuItemName);  // Hiển thị tên món ăn lên jTextField2
                jTextField3.setText(selectedMenuItemName);  // Hiển thị tên món ăn lên jTextField2

            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jtfslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfslActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order_item().setVisible(true);
            }
        });
    }
  
    private void loadMenuItems() {
    // Lấy danh sách món ăn từ cơ sở dữ liệu
    List<MenuItem> menuItems = dbHelper.getMenuItemsFromDatabase();
    // Tạo DefaultListModel và thêm tên món ăn vào đó
    DefaultListModel<String> listModel = new DefaultListModel<>();
    for (MenuItem item : menuItems) {
        listModel.addElement(item.getName());  // Thêm tên món ăn vào listModel
    }

    // Cập nhật jList1 với listModel
    jList1.setModel(listModel);  // jList1 vẫn là JList<String>

    // Truyền danh sách món ăn vào MenuItemRenderer
    MenuItemRenderer renderer = new MenuItemRenderer();
    renderer.setMenuItems(menuItems);  // Truyền danh sách món ăn vào Renderer
    jList1.setCellRenderer(renderer);  // Sử dụng MenuItemRenderer để hiển thị tên, hình ảnh và giá
}

private MenuItem getMenuItemByName(String name) {
    // Duyệt qua danh sách menuItems để tìm món ăn theo tên
    List<MenuItem> menuItems = dbHelper.getMenuItemsFromDatabase();
    for (MenuItem item : menuItems) {
        if (item.getName().equalsIgnoreCase(name)) {  // So sánh tên món ăn
            return item;  // Trả về món ăn nếu tên khớp
        }
    }
    return null;  // Nếu không tìm thấy món ăn, trả về null
}

private void loadDataGroupedByOrder() {
    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    tableModel.setRowCount(0);  // Làm sạch bảng trước khi cập nhật

    try (Connection conn = ConnectSQL.getConnection()) {
        if (conn != null) {
            // Truy vấn có thêm trường tongtien từ order_item
            String query = "SELECT order_id, menu_item_id, name, quantity, price, tongtien FROM order_item ORDER BY order_id";

            try (PreparedStatement stmt = conn.prepareStatement(query)) {
                ResultSet rs = stmt.executeQuery();

                long previousOrderId = -1;
                StringBuilder items = new StringBuilder();
                StringBuilder quantities = new StringBuilder();
                StringBuilder prices = new StringBuilder();
                StringBuilder menuItemIds = new StringBuilder();
                double totalAmount = 0.0;

                while (rs.next()) {
                    long orderId = rs.getLong("order_id");
                    long menuItemId = rs.getLong("menu_item_id");
                    String name = rs.getString("name");
                    int quantity = rs.getInt("quantity");
                    double price = rs.getDouble("price");
                    double tongtien = rs.getDouble("tongtien");  // ✅ lấy từ DB

                    // Nếu orderId thay đổi → thêm dòng cũ vào bảng
                    if (orderId != previousOrderId && previousOrderId != -1) {
                        tableModel.addRow(new Object[]{
                            quantities.toString(),
                            menuItemIds.toString(),
                            previousOrderId,
                            items.toString(),
                            prices.toString(),
                            totalAmount
                        });

                        // Reset biến
                        items.setLength(0);
                        quantities.setLength(0);
                        prices.setLength(0);
                        menuItemIds.setLength(0);
                        totalAmount = 0.0;
                    }

                    // Cộng dồn nội dung
                    items.append(name).append("\n");
                    quantities.append(quantity).append("\n");
                    prices.append(price).append("\n");
                    menuItemIds.append(menuItemId).append("\n");
                    totalAmount += tongtien;

                    previousOrderId = orderId;
                }

                // Thêm dòng cuối cùng
                if (previousOrderId != -1) {
                    tableModel.addRow(new Object[]{
                        quantities.toString(),
                        menuItemIds.toString(),
                        previousOrderId,
                        items.toString(),
                        prices.toString(),
                        totalAmount
                    });
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu: " + e.getMessage());
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL: " + e.getMessage());
    }

    // Cập nhật giao diện bảng
    jTable1.setModel(tableModel);
    customizeTableForMultiLine();
    jTable1.setDefaultEditor(Object.class, null);
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
    //setRowHeight(jTable1);
}


private boolean isMenuItemExistInOrder(long menuItemId, long orderId) {
    String query = "SELECT * FROM order_item WHERE menu_item_id = ? AND order_id = ?";
    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(query)) {
        
        stmt.setLong(1, menuItemId);  // ID món ăn
        stmt.setLong(2, orderId);      // ID đơn hàng
        
        try (ResultSet rs = stmt.executeQuery()) {
            return rs.next();  // Nếu có món ăn trong đơn hàng, trả về true
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;  // Nếu không có món ăn trong đơn hàng, trả về false
}

private void addItemToOrder(long selectedMenuItemId, int quantity, double selectedMenuItemPrice, String selectedMenuItemName, long orderId) {
    // Kiểm tra xem món ăn đã có trong đơn hàng chưa
    if (isMenuItemExistInOrder(selectedMenuItemId, orderId)) {
        // Nếu món ăn đã có, cập nhật số lượng
        String query = "SELECT quantity FROM order_item WHERE menu_item_id = ? AND order_id = ?";
        try (Connection conn = ConnectSQL.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setLong(1, selectedMenuItemId);
            stmt.setLong(2, orderId);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    int currentQuantity = rs.getInt("quantity");
                    int newQuantity = currentQuantity + quantity;  // Cộng thêm số lượng mới
                    updateMenuItemQuantity(selectedMenuItemId, orderId, newQuantity);  // Cập nhật số lượng
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    } else {
        // Nếu món ăn chưa có, thêm vào đơn hàng
        String sql = "INSERT INTO order_item (menu_item_id, quantity, price, order_id, name, tongtien) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = ConnectSQL.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            double total = quantity * selectedMenuItemPrice;  // Tính tổng tiền

            stmt.setLong(1, selectedMenuItemId);  // ID món ăn
            stmt.setInt(2, quantity);              // Số lượng món ăn
            stmt.setDouble(3, selectedMenuItemPrice);  // Giá của món ăn
            stmt.setLong(4, orderId);             // Order ID
            stmt.setString(5, selectedMenuItemName);  // Tên món ăn
            stmt.setDouble(6, total);  // Tổng tiền (tính từ quantity * price)

            stmt.executeUpdate();  // Thêm món ăn vào cơ sở dữ liệu

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Xóa dòng "Chưa có món ăn" nếu có
    String deleteQuery = "DELETE FROM order_item WHERE order_id = ? AND name = 'Chưa có món ăn'";
    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(deleteQuery)) {

        stmt.setLong(1, orderId);
        stmt.executeUpdate();  // Xóa dòng "Chưa có món ăn"

    } catch (SQLException e) {
        e.printStackTrace();
    }

    // Cập nhật lại JTable sau khi thêm hoặc cập nhật món ăn
    loadDataGroupedByOrder();
    customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
System.out.println("Row height: " + jTable1.getRowHeight(0));


}


private void searchOrderItemsByOrderId() {
    String timkiem = jTextField1.getText();  // Lấy giá trị người dùng nhập vào từ TextField

    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    tableModel.setRowCount(0);  // Làm sạch bảng trước khi cập nhật

    // Kiểm tra nếu người dùng không nhập gì
    if (timkiem.isEmpty()) {
        loadDataGroupedByOrder();  // Nếu không có gì nhập vào, tải lại toàn bộ dữ liệu
        customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
        return;  // Dừng lại ở đây nếu không có gì nhập vào
    }

    // Kiểm tra nếu đầu vào không phải là số
    try {
        Long.parseLong(timkiem);  // Cố gắng chuyển đổi đầu vào thành số
    } catch (NumberFormatException e) {
        // Nếu có lỗi chuyển đổi, hiển thị thông báo lỗi và dừng hàm
        JOptionPane.showMessageDialog(this, "Vui lòng nhập một số hợp lệ!", "Lỗi tìm kiếm", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Nếu là số hợp lệ, tiếp tục truy vấn cơ sở dữ liệu
    try (Connection conn = ConnectSQL.getConnection()) {
        if (conn != null) {
            // Câu lệnh SQL tìm kiếm theo order_id
            String query = "SELECT * FROM order_item WHERE order_id = ?";
            try (PreparedStatement stmt = conn.prepareStatement(query)) {
                stmt.setLong(1, Long.parseLong(timkiem));  // Lọc theo order_id

                ResultSet rs = stmt.executeQuery();
                long previousOrderId = -1;  // Khởi tạo trước là không có order_id
                StringBuilder items = new StringBuilder(); // Chứa danh sách món ăn
                StringBuilder quantities = new StringBuilder(); // Chứa số lượng món ăn
                StringBuilder prices = new StringBuilder(); // Chứa giá món ăn
                StringBuilder menuItemIds = new StringBuilder(); // Chứa menu_item_id
                double totalAmount = 0; // Tổng tiền cho mỗi order

                while (rs.next()) {
                    long orderId = rs.getLong("order_id");
                    long menuItemId = rs.getLong("menu_item_id"); // Lấy menu_item_id
                    String name = rs.getString("name");
                    int quantity = rs.getInt("quantity");
                    double price = rs.getDouble("price");

                    double total = quantity * price;
                    totalAmount += total; // Cộng tổng tiền vào order

                    // Nếu orderId thay đổi thì mới thêm một dòng mới vào bảng
                    if (orderId != previousOrderId && previousOrderId != -1) {
                        // Thêm dữ liệu cho order cũ vào bảng
                        tableModel.addRow(new Object[]{
                                quantities.toString(),       // Số lượng
                                menuItemIds.toString(),      // menu_item_id
                                previousOrderId,             // Order ID
                                items.toString(),            // Tên món ăn
                                prices.toString(),           // Giá món ăn
                                totalAmount                  // Tổng tiền cho toàn bộ món ăn
                        });
                        items.setLength(0); // Reset items
                        quantities.setLength(0); // Reset quantities
                        prices.setLength(0); // Reset prices
                        menuItemIds.setLength(0); // Reset menuItemIds
                        totalAmount = 0; // Reset tổng tiền
                    }

                    // Cập nhật dữ liệu cho món ăn trong cùng một order_id
                    items.append(name).append("\n");  // Thêm món ăn mới với \n
                    quantities.append(quantity).append("\n");  // Thêm số lượng mới với \n
                    prices.append(price).append("\n");  // Thêm giá món ăn mới với \n
                    menuItemIds.append(menuItemId).append("\n"); // Thêm menu_item_id mới với \n

                    previousOrderId = orderId;
                }

                // Thêm dữ liệu cuối cùng cho orderId cuối cùng
                if (previousOrderId != -1) {
                    tableModel.addRow(new Object[]{
                            quantities.toString(),        // Số lượng
                            menuItemIds.toString(),       // menu_item_id
                            previousOrderId,              // Order ID
                            items.toString(),             // Tên món ăn
                            prices.toString(),            // Giá món ăn
                            totalAmount                   // Tổng tiền cho toàn bộ món ăn
                    });
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi truy vấn cơ sở dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    // Cập nhật lại bảng sau khi thêm dữ liệu
    jTable1.setModel(tableModel);

    // Áp dụng renderer cho JTable
    //jTable1.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
    customizeTableForMultiLine();
    // Tự động thay đổi chiều cao hàng
//    setRowHeight(jTable1);
}

private void deleteItemFromOrder(String itemName, long orderId) {
    String sql = "DELETE FROM order_item WHERE name = ? AND order_id = ?";
    String checkSql = "SELECT COUNT(*) FROM order_item WHERE order_id = ?";
    String insertEmptySql = "INSERT INTO order_item (order_id, menu_item_id, name, quantity, price, tongtien) VALUES (?, ?, ?, ?, ?, ?)";

    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, itemName);
        stmt.setLong(2, orderId);

        int rowsAffected = stmt.executeUpdate();

        if (rowsAffected > 0) {
            // Sau khi xóa xong, kiểm tra xem đơn hàng còn món nào không
            try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                checkStmt.setLong(1, orderId);
                ResultSet rs = checkStmt.executeQuery();

                if (rs.next()) {
                    int count = rs.getInt(1);

                    if (count == 0) {
                        // Chèn dòng trống nếu không còn món nào
                        try (PreparedStatement insertStmt = conn.prepareStatement(insertEmptySql)) {
                            insertStmt.setLong(1, orderId);
                            insertStmt.setLong(2, 0); // menu_item_id giả
                            insertStmt.setString(3, "--Không có món--");
                            insertStmt.setInt(4, 0);   // quantity
                            insertStmt.setDouble(5, 0); // price
                            insertStmt.setDouble(6, 0); // tongtien
                            insertStmt.executeUpdate();
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Món ăn đã được xóa.");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy món ăn trong đơn hàng.");
        }

        // Cập nhật lại tổng tiền đơn hàng
        //updateTotalAmountOfOrder(orderId);
        loadDataGroupedByOrder();
        customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa món ăn: " + e.getMessage());
    }
}

private void customizeTableForMultiLine() {
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(new MultiLineCellRenderer());
    }
}
public void updateRowHeights(JTable table) {
    for (int row = 0; row < table.getRowCount(); row++) {
        int maxHeight = table.getRowHeight();  // Giá trị mặc định, hoặc bạn đặt cố định

        for (int column = 0; column < table.getColumnCount(); column++) {
            TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
            Component comp = table.prepareRenderer(cellRenderer, row, column);
            maxHeight = Math.max(comp.getPreferredSize().height, maxHeight);
        }

        table.setRowHeight(row, maxHeight);
    }
}

//
//private void setRowHeight(JTable table) {
//    for (int row = 0; row < table.getRowCount(); row++) {
//        int rowHeight = 0;
//        for (int column = 0; column < table.getColumnCount(); column++) {
//            TableCellRenderer renderer = table.getCellRenderer(row, column);
//            Component comp = table.prepareRenderer(renderer, row, column);
//            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
//        }
//        table.setRowHeight(row, rowHeight);
//    }
//}
private double getItemPrice(long menuItemId) {
    double price = 0.00;
    String sql = "SELECT price FROM order_item WHERE menu_item_id = ?";
    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setLong(1, menuItemId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            price = rs.getDouble("price");  // Lấy giá món ăn từ cơ sở dữ liệu
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return price;
}
private void updateMenuItemQuantity(long menuItemId, long orderId, int newQuantity) {
    String sql = "UPDATE order_item SET quantity = ?, tongtien = ? WHERE menu_item_id = ? AND order_id = ?";

    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        double total = newQuantity * getItemPrice(menuItemId);  // Tính lại tổng tiền

        stmt.setInt(1, newQuantity);  // Cập nhật số lượng mới
        stmt.setDouble(2, total);     // Cập nhật tổng tiền
        stmt.setLong(3, menuItemId);  // ID món ăn
        stmt.setLong(4, orderId);     // ID đơn hàng

        stmt.executeUpdate();  // Cập nhật cơ sở dữ liệu

    } catch (SQLException e) {
        e.printStackTrace();
    }
}
private void updateMenuItemQuantity(String itemName, long orderId, int newQuantity) {
    String sql = "UPDATE order_item SET quantity = ?, tongtien = ? WHERE name = ? AND order_id = ?";

    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        double price = getItemPrice(itemName); // Lấy giá từ bảng menu_items
        double total = newQuantity * price;

        stmt.setInt(1, newQuantity);
        stmt.setDouble(2, total);
        stmt.setString(3, itemName);
        stmt.setLong(4, orderId);

        stmt.executeUpdate();
        loadDataGroupedByOrder();
        customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
        customizeTableForMultiLine();
updateRowHeights(jTable1);  // 👈 gọi thêm dòng này!
        

        JOptionPane.showMessageDialog(this, "Sửa số lượng và tổng tiền thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật: " + e.getMessage());
    }
}

// Lấy giá món ăn từ cơ sở dữ liệu dựa trên tên món
private double getItemPrice(String itemName) {
    double price = 0.00;
    String sql = "SELECT price FROM menu_item WHERE name = ?"; // Giả sử giá được lưu trong bảng menu_item

    try (Connection conn = ConnectSQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setString(1, itemName);  // Truy vấn theo tên món ăn
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            price = rs.getDouble("price");  // Lấy giá món ăn từ cơ sở dữ liệu
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return price;  // Trả về giá món ăn
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jtfsl;
    // End of variables declaration//GEN-END:variables
}
