/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import cafe_project.*;
import java.awt.CardLayout;
import java.awt.Color;
//import panel.*;
import panel.ConnectSQL;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import cafe_project.DashBoard;
/**
 *
 * @author Nguyen Van Chien
 */
public class orders extends javax.swing.JPanel {
    private DashBoard dashboard;

    /**
     * Creates new form NewJPanel
     */
    public orders(DashBoard dashboard) {
    this.dashboard = dashboard;
    initComponents();
    initComponents();
           loadStaffAndTableData();
        Loaddata();
        // Vô hiệu hóa chỉnh sửa trên JDateChooser
        jdc1.setEnabled(false);
        jdc1.setDate(new java.util.Date());
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jtf4 = new javax.swing.JTextField();
        jbt4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jdc1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox<>();
        jcb4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcb2 = new javax.swing.JComboBox<>();
        jcb3 = new javax.swing.JComboBox<>();
        jbt5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jButton5.setText("Đơn trong ca");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jtf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf4ActionPerformed(evt);
            }
        });

        jbt4.setText("Tìm kiếm");
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Ngày đặt hàng", "Trạng thái", "Mã nhân viên", "Mã bàn", "Phương thức mua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đơn hàng"));

        jLabel1.setText("Mã đơn hàng");

        jLabel2.setText("Ngày đặt hàng");

        jtf1.setEditable(false);
        jtf1.setBackground(new java.awt.Color(255, 255, 255));
        jtf1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Trạng thái");

        jLabel4.setText("Mã nhân viên");

        jLabel5.setText("Mã bàn");

        jLabel6.setText("Phương thức mua");

        jcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDING", "SERVED", "PAID" }));
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jcb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINE_IN", "TAKEAWAY", " " }));
        jcb4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb4ItemStateChanged(evt);
            }
        });
        jcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb4ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        jcb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        jbt5.setText("Làm mới");
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb4, 0, 158, Short.MAX_VALUE)
                            .addComponent(jcb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbt5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Tìm kiếm:");

        jButton4.setText("Chi tiết đơn hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton4)
                        .addGap(89, 89, 89)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf4ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        Search();        // TODO add your handling code here:
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jtb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseClicked
        int row = jtb1.getSelectedRow();  // Lấy chỉ số dòng được chọn
        if (row >= 0) {
            String orderId = jtb1.getValueAt(row, 0).toString();
            String orderDateStr = jtb1.getValueAt(row, 1).toString();  // dạng chuỗi
            String status = jtb1.getValueAt(row, 2).toString();
            String staffId = jtb1.getValueAt(row, 3).toString();
            String tableId = jtb1.getValueAt(row, 4).toString();
            String orderType = jtb1.getValueAt(row, 5).toString();

            // Gán vào các ô nhập
            jtf1.setText(orderId);

            // Chuyển chuỗi thành kiểu Date rồi gán vào JDateChooser
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");  // định dạng ngày giống như trong DB
                Date date = sdf.parse(orderDateStr);
                jdc1.setDate(date);  // jdcOrderDate là JDateChooser
            } catch (Exception e) {
                e.printStackTrace();
            }

            jcb1.setSelectedItem(status);
            jcb2.setSelectedItem(staffId);
            jcb3.setSelectedItem(tableId);
            jcb4.setSelectedItem(orderType);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtb1MouseClicked

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jcb4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb4ItemStateChanged

        if (jcb4.getSelectedItem() != null) {
            String selectedOrderType = jcb4.getSelectedItem().toString().trim();

            if ("TAKEAWAY".equals(selectedOrderType)) {
                // Nếu chọn "Mang về", đặt giá trị rỗng cho jcb3 và vô hiệu hóa JComboBox bàn
                jcb3.setSelectedIndex(-1);  // Đặt giá trị rỗng (không có gì) cho jcb3
                jcb3.setEnabled(false);  // Vô hiệu hóa jcb3
            } else {
                // Nếu chọn "Ăn tại quán", cho phép chọn bàn
                jcb3.setEnabled(true);  // Bật lại JComboBox bàn
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb4ItemStateChanged

    private void jcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb4ActionPerformed

    }//GEN-LAST:event_jcb4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Loirong()) {
            return;
        }
        // Kiểm tra trạng thái trong jcb1
        String selectedStatus = jcb1.getSelectedItem().toString().trim();  // Lấy trạng thái từ JComboBox
        if (!"PENDING".equals(selectedStatus)) {
            // Nếu không phải "PENDING", hiển thị thông báo cảnh báo
            JOptionPane.showMessageDialog(null, "Bạn phải chọn trạng thái 'PENDING' để thêm đơn hàng!",
                "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;  // Dừng lại không thực hiện thêm đơn hàng
        }

        // Kiểm tra nếu id đã tồn tại
        if (isIdExist()) {
            JOptionPane.showMessageDialog(null, "ID đã tồn tại!");
            return;
        }

        // Kiểm tra nếu bàn đã được chọn và đang sử dụng
        Object selectedItem = jcb3.getSelectedItem();
        if (selectedItem != null) {
            long selectedTableId = Long.parseLong(selectedItem.toString().trim());

            if (isTableAlreadyUsed(selectedTableId)) {
                JOptionPane.showMessageDialog(this, "Bàn này đã được sử dụng, vui lòng chọn bàn khác!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return; // Dừng lại không thực hiện thêm đơn hàng
            }
        }
        // Nếu selectedItem == null thì bỏ qua kiểm tra và tiếp tục xử lý đơn hàng

        // Thêm đơn hàng nếu tất cả kiểm tra hợp lệ
        ADD();
        Loaddata();
        //loadOrdersData(); // Tải lại dữ liệu sau khi thêm đơn hàng TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jtb1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy table_id hiện tại từ dòng đã chọn
        long currentTableId = Long.parseLong(jtb1.getValueAt(selectedRow, 4).toString());

        // Lấy table_id mới được chọn từ combobox
        Object selectedItem = jcb3.getSelectedItem();
        if (selectedItem != null) {
            long newTableId = Long.parseLong(selectedItem.toString().trim());

            // Nếu người dùng đổi bàn => mới kiểm tra bàn có đang sử dụng không
            if (newTableId != currentTableId) {
                if (isTableAlreadyUsed(newTableId)) {
                    JOptionPane.showMessageDialog(this, "Bàn này đã được sử dụng, vui lòng chọn bàn khác!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }

        // Gọi hàm cập nhật đơn hàng
        UpdateOrder();

        // Kiểm tra lỗi rỗng
        if (Loirong()) {
            return;
        }

        // Load lại dữ liệu
        Loaddata();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Delete();
        Loaddata();// cột 0 chứa id
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        loadOrdersData();
        //Loaddata();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    dashboard.setMainPanelContent(new order_item());    
    }//GEN-LAST:event_jButton4ActionPerformed
public void Loaddata() {
    DefaultTableModel model = (DefaultTableModel) jtb1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    try (Connection conn = ConnectSQL.getConnection()) {
        String sql = "SELECT * FROM orders";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getLong("order_id"),
                rs.getTimestamp("order_time"),
                rs.getString("status"),
                rs.getLong("staff_id"),
                rs.getLong("table_id"),
                rs.getString("order_type")
            });
        }

        // Reset các input nếu có
        jtf1.setText("");
        Calendar calendar = Calendar.getInstance();  // Lấy ngày hiện tại
        jdc1.setDate(calendar.getTime()); ;
        jcb1.setSelectedIndex(-1);
        jcb2.setSelectedIndex(-1);
        jcb3.setSelectedIndex(-1);
        jcb3.setEnabled(true);

        jcb4.setSelectedIndex(-1);

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi tải dữ liệu: " + e.getMessage());
    }
}
   public void ADD() {
    try {
        Connection conn = ConnectSQL.getConnection();

        // Lấy thông tin từ các trường nhập liệu
        String status = jcb1.getSelectedItem().toString().trim();
        String staffIdStr = jcb2.getSelectedItem().toString().trim(); // hoặc jtfStaffId.getText()
        String tableIdStr = jcb3.getSelectedItem() != null ? jcb3.getSelectedItem().toString().trim() : null;
        String orderType = jcb4.getSelectedItem().toString().trim();

        // Convert về kiểu long
        long staff_id = Long.parseLong(staffIdStr);
        long table_id = (tableIdStr != null) ? Long.parseLong(tableIdStr) : 0;

        // Lấy thời gian hiện tại làm order_date
        Timestamp now = new Timestamp(System.currentTimeMillis());

        // Tạo câu lệnh SQL để thêm đơn hàng vào bảng orders
        String sql = "INSERT INTO orders (order_time, status, staff_id, table_id, order_type) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

        stmt.setTimestamp(1, now);
        stmt.setString(2, status);
        stmt.setLong(3, staff_id);
        stmt.setLong(4, table_id);
        stmt.setString(5, orderType);

        int thucthi = stmt.executeUpdate();  // Thêm đơn hàng vào bảng

        // Kiểm tra kết quả thêm đơn hàng
        if (thucthi > 0) {
            // Lấy order_id mới tạo
            ResultSet generatedKeys = stmt.getGeneratedKeys();
            if (generatedKeys.next()) {
                long orderId = generatedKeys.getLong(1);  // Lấy order_id mới

                // Thêm một bản ghi mới vào bảng order_item với order_id mới
                // Bạn có thể dùng giá trị mặc định (tên món là "Chưa có món ăn", số lượng là 0, giá là 0)
                String insertOrderItemQuery = "INSERT INTO order_item (order_id, name, quantity, price) VALUES (?, ?, ?, ?)";
                try (PreparedStatement stmtItem = conn.prepareStatement(insertOrderItemQuery)) {
                    stmtItem.setLong(1, orderId);  // Truyền order_id vào bảng order_item
                    stmtItem.setString(2, "Chưa có món ăn");  // Truyền tên món vào bảng order_item
                    stmtItem.setInt(3, 0);  // Số lượng mặc định là 0
                    stmtItem.setDouble(4, 0);  // Giá mặc định là 0
                    stmtItem.executeUpdate();  // Thêm vào bảng order_item
                }

                // Hiển thị thông báo thành công
                JOptionPane.showMessageDialog(this, "Đơn hàng mới đã được tạo thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không thể thêm đơn hàng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi SQL: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi định dạng số: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

    public void UpdateOrder() {
    try {
        
        int selectedRow = jtb1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần sửa!");
            return;
        }
        Connection conn = ConnectSQL.getConnection();
        
        String id = jtf1.getText();                      // Trường ID đơn hàng
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        String order_time = sdf.format(jdc1.getDate());             // Trường thời gian đặt hàng
        String status = jcb1.getSelectedItem().toString();  // Trạng thái (PAID, PENDING...)
        String staff_id = jcb2.getSelectedItem().toString();               // Mã nhân viên
        String table_id = (jcb3.getSelectedItem() != null) ? jcb3.getSelectedItem().toString() : null;             // Mã bàn
        String order_type = jcb4.getSelectedItem().toString();  // Loại đơn hàng
        
        String sql = "UPDATE orders SET order_time = ?, status = ?, staff_id = ?, table_id = ?, order_type = ? WHERE order_id = ?";
        
        PreparedStatement stmt = conn.prepareStatement(sql);
        
        stmt.setString(1, order_time);
        stmt.setString(2, status);
        stmt.setString(3, staff_id);
        stmt.setString(4, table_id);
        stmt.setString(5, order_type);
        stmt.setString(6, id);  // id ở cuối vì nằm trong WHERE
        
        int result = stmt.executeUpdate();
        
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Cập nhật đơn hàng thành công!");
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy đơn hàng với ID: " + id);
        }
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi cập nhật đơn hàng: " + e.getMessage());
    }
}
    public void Delete() {
    try {
        Connection conn = ConnectSQL.getConnection();

        // Xác nhận xóa tất cả các đơn hàng có trạng thái "PAID"
        int confirm = JOptionPane.showConfirmDialog(null, 
            "Bạn có chắc chắn muốn xóa tất cả các đơn hàng có trạng thái 'PAID'?", 
            "Xác nhận xóa", 
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return; // Dừng lại nếu chọn "No"
        }

        // Lấy tất cả các đơn hàng có trạng thái "PAID" từ bảng orders
        String selectOrdersSql = "SELECT * FROM orders WHERE status = 'PAID'";
        try (PreparedStatement stmt = conn.prepareStatement(selectOrdersSql)) {
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                long orderId = rs.getLong("order_id");
                Timestamp orderTime = rs.getTimestamp("order_time");
                String status = rs.getString("status");
                long staffId = rs.getLong("staff_id");
                long tableId = rs.getLong("table_id");
                String orderType = rs.getString("order_type");

                // Chuyển đơn hàng vào bảng order_history
                String insertHistorySql = "INSERT INTO orders_history (order_id, order_time, status, staff_id, table_id, order_type) VALUES (?, ?, ?, ?, ?, ?)";
                try (PreparedStatement stmtInsert = conn.prepareStatement(insertHistorySql)) {
                    stmtInsert.setLong(1, orderId);
                    stmtInsert.setTimestamp(2, orderTime);
                    stmtInsert.setString(3, status);
                    stmtInsert.setLong(4, staffId);
                    stmtInsert.setLong(5, tableId);
                    stmtInsert.setString(6, orderType);
                    stmtInsert.executeUpdate();
                }

                // Lấy tất cả các món ăn trong bảng order_item liên quan đến orderId
                String selectItemsSql = "SELECT * FROM order_item WHERE order_id = ?";
                try (PreparedStatement stmtItems = conn.prepareStatement(selectItemsSql)) {
                    stmtItems.setLong(1, orderId);
                    ResultSet rsItems = stmtItems.executeQuery();

                    // Chuyển tất cả các món ăn vào bảng order_item_history
                    while (rsItems.next()) {
                        long menuItemId = rsItems.getLong("menu_item_id");
                        String itemName = rsItems.getString("name");
                        int quantity = rsItems.getInt("quantity");
                        double price = rsItems.getDouble("price");
                        double total = rsItems.getDouble("tongtien");

                        // Chèn vào bảng order_item_history
                        String insertItemHistorySql = "INSERT INTO order_item_history (quantity, menu_item_id, order_id, name, price, tongtien) VALUES (?, ?, ?, ?, ?, ?)";
                        try (PreparedStatement stmtItemHistory = conn.prepareStatement(insertItemHistorySql)) {
                            stmtItemHistory.setInt(1, quantity);
                            stmtItemHistory.setLong(2, menuItemId);
                            stmtItemHistory.setLong(3, orderId);
                            stmtItemHistory.setString(4, itemName);
                            stmtItemHistory.setDouble(5, price);
                            stmtItemHistory.setDouble(6, total);
                            stmtItemHistory.executeUpdate();
                        }
                    }
                }

                // Xóa các mục trong bảng order_item có liên quan đến orderId
                String deleteOrderItemsSql = "DELETE FROM order_item WHERE order_id = ?";
                try (PreparedStatement stmtDeleteItems = conn.prepareStatement(deleteOrderItemsSql)) {
                    stmtDeleteItems.setLong(1, orderId);
                    stmtDeleteItems.executeUpdate();
                }

                // Xóa đơn hàng trong bảng orders
                String deleteOrderSql = "DELETE FROM orders WHERE order_id = ?";
                try (PreparedStatement stmtDeleteOrder = conn.prepareStatement(deleteOrderSql)) {
                    stmtDeleteOrder.setLong(1, orderId);
                    stmtDeleteOrder.executeUpdate();
                }
            }

            JOptionPane.showMessageDialog(null, "Tất cả các đơn hàng 'PAID' đã được xóa và chuyển vào lịch sử!");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi xóa đơn hàng: " + e.getMessage());
    }
}


    
    public boolean Loirong() {
     if (jdc1.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn THỜI GIAN ĐẶT HÀNG");
        return true;
    } else if (jcb1.getSelectedItem() == null || jcb1.getSelectedItem().toString().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn TRẠNG THÁI đơn hàng");
        return true;
    } else if (jcb2.getSelectedItem() == null || jcb2.getSelectedItem().toString().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn MÃ NHÂN VIÊN");
        return true;
    }  else if (jcb4.getSelectedItem() == null || jcb4.getSelectedItem().toString().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn LOẠI ĐƠN HÀNG");
        return true;
    }

    return false; // Không lỗi
}
    public boolean isIdExist() {
    String id = jtf1.getText().trim();  // Lấy trực tiếp từ ô nhập jtf1

    try {
        Connection conn = ConnectSQL.getConnection();
        String sql = "SELECT order_id FROM orders WHERE order_id = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, id);
        ResultSet rs = stmt.executeQuery();

        return rs.next(); // true nếu ID đã tồn tại
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi kiểm tra ID: " + e.getMessage());
        return true; // Trả về true để an toàn trong trường hợp có lỗi
    }
}

public void resetForm() {
     jtf1.setText("");
        Calendar calendar = Calendar.getInstance();  // Lấy ngày hiện tại
        jdc1.setDate(calendar.getTime()); ;
        jcb1.setSelectedIndex(-1);
        jcb2.setSelectedIndex(-1);
        jcb3.setSelectedIndex(-1);
        jcb4.setSelectedIndex(-1);
        Loaddata();
}
public void Search() {
    String timkiem = jtf4.getText();  // Nhận giá trị tìm kiếm từ ô nhập liệu

    // Kiểm tra xem đầu vào có trống không
    if (timkiem.isEmpty()) {
        Loaddata();  // Nếu không có gì nhập vào, tải lại toàn bộ dữ liệu
        return;
    }

    // Kiểm tra nếu đầu vào không phải là số
    try {
        Long.parseLong(timkiem);  // Cố gắng chuyển đổi đầu vào thành số
    } catch (NumberFormatException e) {
        // Nếu có lỗi chuyển đổi, hiển thị thông báo lỗi và dừng hàm
        JOptionPane.showMessageDialog(this, "Vui lòng nhập một số hợp lệ!", "Lỗi tìm kiếm", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jtb1.getModel();
    model.setRowCount(0);  // Xóa dữ liệu cũ trong bảng

    // Câu lệnh SQL tìm kiếm theo trường id
    String sql = "SELECT * FROM orders WHERE order_id = ?";
    try (Connection conn = ConnectSQL.getConnection()) {
        PreparedStatement stmt = conn.prepareStatement(sql);

        // Cập nhật tham số tìm kiếm chỉ theo id
        stmt.setLong(1, Long.parseLong(timkiem));  // Tìm theo id (bigint)

        ResultSet rs = stmt.executeQuery();

        // Lặp qua kết quả trả về và thêm vào bảng
        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getLong("order_id"),
                rs.getString("order_time"),
                rs.getString("status"),
                rs.getLong("staff_id"),
                rs.getLong("table_id"),
                rs.getString("order_type")
            };
            model.addRow(row);  // Thêm một dòng vào bảng
        }
    } catch (SQLException e) {
        e.printStackTrace();  // In ra lỗi nếu có
    }
}

// Lấy danh sách nhân viên (staff_id) và bàn (table_id) từ cơ sở dữ liệu và điền vào JComboBox
private void loadStaffAndTableData() {
    try (Connection conn = ConnectSQL.getConnection()) {
        // Lấy danh sách nhân viên từ bảng staff
        String staffQuery = "SELECT employeeID FROM employee";
        try (PreparedStatement stmt = conn.prepareStatement(staffQuery)) {
            ResultSet rs = stmt.executeQuery();
            jcb2.removeAllItems();  // Xóa các mục cũ trong JComboBox
            while (rs.next()) {
                // Thêm nhân viên vào JComboBox
                jcb2.addItem(rs.getString("employeeID"));  // staff_id - staff_name
            }
        }

        // Lấy danh sách bàn từ bảng table
        String tableQuery = "SELECT IdTable FROM tablemanagement where Status=N'Tắt'";
        try (PreparedStatement stmt = conn.prepareStatement(tableQuery)) {
            ResultSet rs = stmt.executeQuery();
            jcb3.removeAllItems();  // Xóa các mục cũ trong JComboBox
            while (rs.next()) {
                // Lấy table_id và table_name từ cơ sở dữ liệu
                long tableId = rs.getLong("IdTable");

                jcb3.addItem(Long.toString(tableId));
  // Thêm bàn vào JComboBox
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
    }
}

private boolean isTableAlreadyUsed(long tableId) {
    // Kiểm tra trong cơ sở dữ liệu xem bàn đã được sử dụng trong đơn hàng nào chưa
    String sql = "SELECT * FROM orders WHERE table_id = ? AND status != 'PAID'";  // Kiểm tra chỉ các bàn chưa được thanh toán
    try (Connection conn = ConnectSQL.getConnection(); 
         PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setLong(1, tableId);
        ResultSet rs = stmt.executeQuery();
        
        return rs.next();  // Nếu có kết quả, nghĩa là bàn đã được sử dụng
    } catch (SQLException e) {
        e.printStackTrace();
        return false;  // Nếu có lỗi kết nối, coi như không tìm thấy bàn đã được sử dụng
    }
}

private void loadOrdersData() {
    DefaultTableModel tableModel = (DefaultTableModel) jtb1.getModel();
    tableModel.setRowCount(0);  // Xóa dữ liệu hiện tại trong bảng

    // Truy vấn dữ liệu từ bảng orders mà trạng thái không phải là 'PAID'
    String query = "SELECT * FROM orders WHERE status != 'PAID'";  // Truy vấn các đơn hàng có trạng thái khác 'PAID'

    try (Connection conn = ConnectSQL.getConnection()) {
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();

        // Lặp qua kết quả trả về và thêm vào bảng
        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getLong("order_id"),              // Order ID
                rs.getString("order_time"),    // Order Time
                rs.getString("status"),        // Status
                rs.getLong("staff_id"),        // Staff ID
                rs.getLong("table_id"),        // Table ID
                rs.getString("order_type")     // Order Type
            };
            tableModel.addRow(row);  // Thêm dòng vào bảng
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JComboBox<String> jcb1;
    private javax.swing.JComboBox<String> jcb2;
    private javax.swing.JComboBox<String> jcb3;
    private javax.swing.JComboBox<String> jcb4;
    private com.toedter.calendar.JDateChooser jdc1;
    private javax.swing.JTable jtb1;
    private javax.swing.JTextField jtf1;
    private javax.swing.JTextField jtf4;
    // End of variables declaration//GEN-END:variables
}
