/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import panel.ConnectSQL;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Nguyen Van Chien
 */
public class revenues extends javax.swing.JPanel {
private JPanel topPanel;
    private JPanel chartPanelContainer;
    private JDateChooser dateChooser;
    private JDateChooser monthChooser;
    private JButton btnSearchByDate;
    private JButton btnSearchByMonth;
    private JButton btnExport;
    private JMonthChooser monthOnlyChooser;
private JYearChooser yearChooser;
    /**
     * Creates new form revenues
     */
    public revenues() {
        initComponents();
         initCustomComponents(); // Phần thêm tìm kiếm ngày và tháng
        loadRevenueChart(null, null); // Hiển thị toàn bộ lúc đầu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1249, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void initCustomComponents() {
        this.setLayout(new BorderLayout());
        
       this.setLayout(new BorderLayout()); // THÊM DÒNG NÀY

        topPanel = new JPanel(new GridLayout(2, 3, 10, 10));
        chartPanelContainer = new JPanel(new BorderLayout());
          
        monthOnlyChooser = new JMonthChooser(); // KHỞI TẠO
        yearChooser = new JYearChooser();       // KHỞI TẠO

        dateChooser = new JDateChooser();
        btnSearchByDate = new JButton("Tìm theo ngày");
        btnSearchByMonth = new JButton("Tìm theo tháng");
        btnExport = new JButton("Xuất doanh thu");

        topPanel.add(new JLabel("Chọn ngày:"));
        topPanel.add(dateChooser);
        topPanel.add(btnSearchByDate);
        topPanel.add(new JLabel("Chọn tháng:"));
        topPanel.add(monthOnlyChooser);
        topPanel.add(yearChooser);

        topPanel.add(btnSearchByMonth);

        // Thêm hàng xuất file dưới cùng
           // Thêm hàng xuất file dưới cùng
        JPanel exportPanel = new JPanel(new BorderLayout());
        exportPanel.add(btnExport, BorderLayout.EAST);

        this.add(topPanel, BorderLayout.NORTH);
        this.add(chartPanelContainer, BorderLayout.CENTER);
        this.add(exportPanel, BorderLayout.SOUTH);

        // Các sự kiện
        btnSearchByDate.addActionListener(e -> {
            Date selectedDate = dateChooser.getDate();
            if (selectedDate != null) {
                String value = new SimpleDateFormat("yyyy-MM-dd").format(selectedDate);
                loadRevenueChart("date = ?", value);
            }
        });

        btnSearchByMonth.addActionListener(e -> {
    int selectedMonth = monthOnlyChooser.getMonth() + 1; // tháng từ 0–11
    int selectedYear = yearChooser.getYear();
    String formattedMonth = String.format("%04d-%02d", selectedYear, selectedMonth);
    loadRevenueChart("DATE_FORMAT(date, '%Y-%m') = ?", formattedMonth);
});


        btnExport.addActionListener(e -> exportRevenueToCSV());
    }
 private void loadRevenueChart(String condition, String value) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String sql = "SELECT date, TotalAmount FROM revenues";
        if (condition != null) {
            sql += " WHERE " + condition;
        }
        sql += " ORDER BY date";

        try (Connection conn = ConnectSQL.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            if (value != null) stmt.setString(1, value);
            ResultSet rs = stmt.executeQuery();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            while (rs.next()) {
                Date date = rs.getDate("date");
                double total = rs.getDouble("TotalAmount");
                dataset.addValue(total, "Doanh thu", sdf.format(date));
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn: " + e.getMessage());
            return;
        }

        JFreeChart chart = ChartFactory.createBarChart(
            "Thống kê Doanh thu",
            "Ngày",
            "Tổng tiền (VND)",
            dataset,
            PlotOrientation.VERTICAL,
            false, true, false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(850, 450));
        chartPanelContainer.removeAll();
        chartPanelContainer.add(chartPanel, BorderLayout.CENTER);
        chartPanelContainer.revalidate();
        chartPanelContainer.repaint();
    }
    //private void loadRevenueChart(String condition, String value) {
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        String sql = "SELECT date, TotalAmount FROM revenues";
//        if (condition != null) {
//            sql += " WHERE " + condition;
//        }
//        sql += " ORDER BY date";
//
//        try (Connection conn = ConnectSQL.getConnection();
//             PreparedStatement stmt = conn.prepareStatement(sql)) {
//            if (value != null) stmt.setString(1, value);
//            ResultSet rs = stmt.executeQuery();
//
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//            while (rs.next()) {
//                Date date = rs.getDate("date");
//                double total = rs.getDouble("TotalAmount");
//                dataset.addValue(total, "Doanh thu", sdf.format(date));
//            }
//
//        } catch (SQLException e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi truy vấn: " + e.getMessage());
//            return;
//        }
//
//        JFreeChart chart = ChartFactory.createBarChart(
//            "Thống kê Doanh thu",
//            "Ngày",
//            "Tổng tiền (VND)",
//            dataset,
//            PlotOrientation.VERTICAL,
//            false, true, false
//        );
//
//        ChartPanel chartPanel = new ChartPanel(chart);
//        chartPanel.setPreferredSize(new Dimension(850, 450));
//        chartPanelContainer.removeAll();
//        chartPanelContainer.add(chartPanel, BorderLayout.CENTER);
//        chartPanelContainer.revalidate();
//        chartPanelContainer.repaint();
 
    private void exportRevenueToCSV() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu doanh thu thành file CSV");
        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            try (Connection conn = ConnectSQL.getConnection();
                 PreparedStatement stmt = conn.prepareStatement("SELECT date, TotalAmount FROM revenues ORDER BY date");
                 ResultSet rs = stmt.executeQuery()) {

                java.io.File file = fileChooser.getSelectedFile();
                if (!file.getName().toLowerCase().endsWith(".csv")) {
                    file = new java.io.File(file.getAbsolutePath() + ".csv");
                }

                try (java.io.FileWriter writer = new java.io.FileWriter(file)) {
                    writer.write("Ngày,Tổng tiền (VND)\n");
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                    while (rs.next()) {
                        String date = sdf.format(rs.getDate("date"));
                        double total = rs.getDouble("TotalAmount");
                        writer.write(date + "," + total + "\n");
                    }

                    JOptionPane.showMessageDialog(this, "Xuất file thành công!");
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất file: " + e.getMessage());
            }
        }
    }

    // Chạy thử độc lập
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Thống kê Doanh thu");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new revenues());
            frame.setSize(950, 600);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
