/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewpanel;

import dinhtuananmodel.Category;
import dinhtuananmodel.CategoryDAO;
import dinhtuananmodel.MenuItem;
import dinhtuananmodel.MenuItemDAO;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.net.URL;
import java.util.Base64;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class CategoryPanel extends javax.swing.JPanel {
    private CategoryDAO categoryDAO = new CategoryDAO();
    private MenuItemDAO menuItemDAO = new MenuItemDAO();
    private DefaultTableModel tableModel;
    private String role;
    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel(String role) {
        this.role=role;
        initComponents();
        tableModel = (DefaultTableModel) jCategoryTable.getModel();
        loadData();

        // Chuyển jItemsPanel sang FlowLayout
        jItemsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        jScrollPaneItems.setBorder(BorderFactory.createTitledBorder("Menu Items"));
    }

    private void applyRolePermissions() {
        boolean isAdmin = "admin".equalsIgnoreCase(role);
        btnadd.setVisible(isAdmin);
        btnUpdate.setVisible(isAdmin);
        btnDeleted.setVisible(isAdmin);
    }
    
    private void loadData() {
        tableModel.setRowCount(0);
        List<Category> list = categoryDAO.getAllCategories();
        for (Category c : list) {
            tableModel.addRow(new Object[]{c.getId(), c.getName()});
        }
    }
    
    private void loadMenuItems(long categoryId) {
        jItemsPanel.removeAll();
        List<MenuItem> items = menuItemDAO.getMenuItemsByCategory(categoryId);
        int cardSize = 110;
        for (MenuItem m : items) {
            JPanel card = new JPanel();
            card.setPreferredSize(new Dimension(cardSize, cardSize));
            card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
            card.setBorder(BorderFactory.createLineBorder(java.awt.Color.GRAY));
            String imgData = m.getImageUrl();
            ImageIcon icon = createIcon(imgData, 60, 60);
            JLabel lblImage = new JLabel(icon);
            lblImage.setAlignmentX(CENTER_ALIGNMENT);
            JLabel lblName = new JLabel(m.getName());
            lblName.setAlignmentX(CENTER_ALIGNMENT);
            JLabel lblPrice = new JLabel(String.format("%,d VNĐ", m.getPrice().longValue()));
            lblPrice.setAlignmentX(CENTER_ALIGNMENT);
            card.add(Box.createVerticalStrut(5));
            card.add(lblImage);
            card.add(Box.createVerticalStrut(5));
            card.add(lblName);
            card.add(Box.createVerticalStrut(3));
            card.add(lblPrice);
            jItemsPanel.add(card);
        }
        jItemsPanel.revalidate();
        jItemsPanel.repaint();
    }
    
    private ImageIcon createIcon(String data, int w, int h) {
        try {
            BufferedImage buf;
            if (data.startsWith("data:image")) {
                byte[] bytes = Base64.getDecoder().decode(data.substring(data.indexOf(",")+1));
                buf = ImageIO.read(new ByteArrayInputStream(bytes));
            } else {
                buf = ImageIO.read(new URL(data));
            }
            Image scaled = buf.getScaledInstance(w, h, Image.SCALE_SMOOTH);
            return new ImageIcon(scaled);
        } catch (Exception ex) {
            BufferedImage fallback = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
            return new ImageIcon(fallback);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCategoryTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textIdCategory = new javax.swing.JTextField();
        textNameCategory = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleted = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPaneItems = new javax.swing.JScrollPane();
        jItemsPanel = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jCategoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCategoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCategoryTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("id:");

        jLabel2.setText("name:");

        btnadd.setText("thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnUpdate.setText("sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeleted.setText("xóa");
        btnDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletedActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNameCategory)))
                        .addGap(52, 52, 52)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleted)))
                .addGap(36, 36, 36)
                .addComponent(btnSearch)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel1)
                    .addComponent(textIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDeleted))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPaneItems.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Menu"));

        jItemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "danh sách món"));
        jItemsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        jScrollPaneItems.setViewportView(jItemsPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneItems, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneItems)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCategoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCategoryTableMouseClicked
        int selectrow=jCategoryTable.getSelectedRow();
        if(selectrow!=-1){
            Object idObj=jCategoryTable.getValueAt(selectrow, 0);
            Object name=jCategoryTable.getValueAt(selectrow, 1);
            textIdCategory.setText(String.valueOf(idObj));
            textNameCategory.setText(String.valueOf(name));
            long id = Long.parseLong(String.valueOf(idObj));
            loadMenuItems(id);
        }
    }//GEN-LAST:event_jCategoryTableMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String nameCategory=textNameCategory.getText();

        if (nameCategory == null || nameCategory.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên danh mục không được để trống!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        nameCategory = nameCategory.trim();
        if (nameCategory.length() > 255) {
            JOptionPane.showMessageDialog(null, "Tên danh mục không được vượt quá " + 255 + " ký tự!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        categoryDAO.insertCategory(nameCategory);
        loadData();
        textNameCategory.setText("");
        textIdCategory.setText("");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        long id =Long.parseLong(textIdCategory.getText());
        String nameCategory=textNameCategory.getText();
        if (nameCategory == null || nameCategory.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên danh mục không được để trống!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        nameCategory = nameCategory.trim();
        if (nameCategory.length() > 255) {
            JOptionPane.showMessageDialog(null, "Tên danh mục không được vượt quá " + 255 + " ký tự!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        categoryDAO.updateCategory(id, nameCategory);
        loadData();
        textNameCategory.setText("");
        textIdCategory.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletedActionPerformed
        long id =Long.parseLong(textIdCategory.getText());
        categoryDAO.deleteCategory(id);
        loadData();
        textNameCategory.setText("");
        textIdCategory.setText("");
    }//GEN-LAST:event_btnDeletedActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // 1. Lấy từ khóa tìm kiếm
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) {
            // Nếu không nhập gì, có thể load lại toàn bộ dữ liệu
            loadData();
            return;
        }

        // 2. Gọi DAO để tìm category theo tên
        List<Category> resultList = categoryDAO.searchCategoriesByName(keyword);

        // 3. Xóa dữ liệu cũ trên tableModel
        tableModel.setRowCount(0);

        // 4. Đổ dữ liệu tìm được lên bảng
        for (Category c : resultList) {
            tableModel.addRow(new Object[]{c.getId(), c.getName()});
        }

        // 5. Xóa các trường nhập liệu (nếu cần)
        textIdCategory.setText("");
        textNameCategory.setText("");

        // 6. Xóa panel món (nếu đang hiển thị)
        jItemsPanel.removeAll();
        jItemsPanel.revalidate();
        jItemsPanel.repaint();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleted;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnadd;
    private javax.swing.JTable jCategoryTable;
    private javax.swing.JPanel jItemsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneItems;
    private javax.swing.JTextField textIdCategory;
    private javax.swing.JTextField textNameCategory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
